# Sunucu Portumuz
server.port=8082

# PostgreSQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/eticaret_db
spring.datasource.username=postgres
# D?KKAT: CMD ekran?nda belirledi?in ?ifreyi buraya yaz (Örn: 1234)
spring.datasource.password=123456

# Önceki hatay? önlemek için PostgreSQL ?ivesini (Dialect) aç?kça belirtiyoruz
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate (JPA) Ayarlar?
# update: Proje çal??t???nda tablo yoksa olu?turur, varsa sadece günceller. Veriyi ASLA silmez!
spring.jpa.hibernate.ddl-auto=update

# Arka planda çal??t?r?lan SQL kodlar?n? konsolda görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=update
